### ISSUE TITLE
希望增加对荧光笔的识别

### ISSUE THREAD

**Issue by shoudeyunkaijianyueming** [tansongchen/obsidian-note-synchronizer#2]
1、荧光笔==1==这种的识别
2、在obsidian to anki中 荧光笔部分是可以直接识别成填空的，也就是obsidian中的==1==在anki中就变成了{{c1::1}} ，==2==变成了{{c1::2}} 
对于我个人而言，obsidian to anki无法很多字段，而老哥这个可以多字段，这也是我见到这个插件超级惊喜
希望老哥能把它进一步完善，谢谢

**Comment by shoudeyunkaijianyueming** [comment]
当然如果能增加荧光填空的功能，希望在设置中增加个选项，来自主决定是否使用这个功能，谢谢

**Comment by shoudeyunkaijianyueming** [comment]
我知道但我不会变成，正则表达式我自己不会写，我现在只用的插件wiki介绍的那几个，我尝试使用过reddit上别的大神写的，因为写的是中文，大神们对应的是英文，总有莫名的不识别。

**Comment by xiaobaicode6** [comment]
大佬 根本同步不到anki怎么解决啊?

**Comment by shoudeyunkaijianyueming** [comment]
抱歉，最近忙，才看到，逻辑上应该没有问题

**Comment by shoudeyunkaijianyueming** [comment]
谢谢

**Comment by shoudeyunkaijianyueming** [comment]
另外我在使用中发现了另一个可变的点，我发了新的issues（国内网上github不方便，最近还忙考试，回复不及时）

**Comment by shoudeyunkaijianyueming** [comment]
对了，希望荧光笔这个能加个是否开启项，因为可能我说的是我的想法，可能有的朋友并不适合，谢谢开发者

**Comment by shoudeyunkaijianyueming** [comment]
老哥填空这个功能能不能先发个release尝尝鲜吖

**Comment by shoudeyunkaijianyueming** [comment]
好的，填空我自己使用尚未发现问题，先关了，有问题再请教你
